swagger: "2.0"
info:
  title: CloudFlare Organization Roles API
  description: The API for managing CloudFlare Organization Roles
  termsOfService: https://www.cloudflare.com/terms/
  version: 1.0.0
host: api.cloudflare.com
basePath: /client/v4
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /organizations/:organization_identifier/roles:
    get:
      summary: Get all available roles for an organization
      description: Get all available roles for an organization
      operationId: cloudflare-organization-roles-api
      responses:
        200:
          description: OK
      tags:
      - ""
  /organizations/:organization_identifier/roles/:identifier:
    get:
      summary: Get information about a specific role for an organization
      description: Get information about a specific role for an organization
      operationId: cloudflare-organization-roles-api
      responses:
        200:
          description: OK
      tags:
      - ""
definitions: []