swagger: "2.0"
info:
  title: Comments API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  api/v1/comments:
    post:
      summary: Create a comment
      description: '          Comments are essentially special forms of events that          appear
        in the stream. They can start a new discussion thread or          optionally,
        reply in another thread.        '
      operationId: create-a-comment
      parameters:
      - type: string
      responses:
        200:
          description: OK
      tags:
      - Comments
  api/v1/comments/:comment_id:
    delete:
      summary: Delete a Comment
      description: ""
      operationId: delete-a-comment
      responses:
        200:
          description: OK
      tags:
      - Comments
    put:
      summary: Edit a Comment
      description: ""
      operationId: edit-a-comment
      parameters:
      - type: string
      responses:
        200:
          description: OK
      tags:
      - Comments
definitions: []