swagger: "2.0"
info:
  title: Analysis API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  n    /api/{version}/analysis/{checkid}:
    n    get:
      summary: Get Root Cause Analysis Results List
      description: '    Returns a list of the latest root cause analysis results for
        a specified check.'
      operationId: get-root-cause-analysis-results-list
      parameters:
      - in: query
        name: from
        description: Return only results with timestamp of first test greater or equal
          to this value. Format is UNIX timestamp.
        type: <td>integer</td>
      - in: query
        name: limit
        description: Limits the number of returned results to the specified quantity.
        type: <td>integer</td>
      - in: query
        name: offset
        description: Offset for listing. (Requires limit.)
        type: <td>integer</td>
      - in: query
        name: to
        description: Return only results with timestamp of first test less or equal
          to this value. Format is UNIX timestamp.
        type: <td>integer</td>
      responses:
        200:
          description: OK
      tags:
      - Analysis
definitions: []