swagger: "2.0"
info:
  title: Credits API
  description: The Credits API.
  version: 1.0.0
host: api.pingdom.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  n    /api/{version}/credits:
    n    get:
      summary: Get Credits List
      description: '    Returns information about remaining checks, SMS credits and
        SMS auto-refill status.'
      operationId: get-credits-list
      responses:
        200:
          description: OK
      tags:
      - Credits
definitions: []