swagger: "2.0"
info:
  title: Probes API
  description: The Probes API.
  version: 1.0.0
host: api.pingdom.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  n    /api/{version}/probes:
    n    get:
      summary: Get Probe Server List
      description: '    Returns a list of all Pingdom probe servers for Uptime and
        Transaction checks.'
      operationId: get-probe-server-list
      parameters:
      - in: query
        name: includedeleted
        description: Include old probes that are no longer in use
        type: <td>boolean</td>
      - in: query
        name: limit
        description: Limits the number of returned probes to the specified quantity.
        type: <td>integer</td>
      - in: query
        name: offset
        description: Offset for listing. (Requires limit.)
        type: <td>integer</td>
      - in: query
        name: onlyactive
        description: Return only active probes.
        type: <td>boolean</td>
      responses:
        200:
          description: OK
      tags:
      - Proves
definitions: []