swagger: "2.0"
info:
  title: Single API
  description: The Single API.
  version: 1.0.0
host: api.pingdom.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  n    /api/{version}/single:
    n    get:
      summary: Make A Single Test
      description: '    Performs a single test using a specified Pingdom probe against
        a specified target. Please note that this method is meant to be used sparingly,
        not to set up your own monitoring solution.'
      operationId: make-a-single-test
      parameters:
      - in: query
        name: host
        description: Target host
        type: <td>string</td>
      - in: query
        name: ipv6
        description: Use ipv6 instead of ipv4
        type: <td>boolean</td>
      - in: query
        name: probeid
        description: Probe identifier
        type: <td>integer</td>
      - in: query
        name: type
        description: Type of test
        type: <td>string (http, httpcustom, tcp, ping, dns,
      responses:
        200:
          description: OK
      tags:
      - Single
definitions: []