swagger: "2.0"
info:
  title: Tags API
  description: The Tags API.
  version: 1.0.0
host: api.serverdensity.io.
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /inventory/tags:
    "":
      summary: Deleting a tag
      description: ""
      operationId: deleting-a-tag
      parameters:
      - in: body
        name: color
        description: The color of the tag in hexcode
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: name
        description: Name of the tag
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: token
        description: Your API token
        schema:
          $ref: '#/definitions/holder'
      responses:
        200:
          description: OK
      tags:
      - Tags
  /tags:
    get:
      summary: List All Tags
      description: List All Tags
      operationId: listAllTags
      parameters:
      - in: query
        name: detailed
        description: Detailed List All Tags
      responses:
        200:
          description: OK
      tags:
      - Tags
definitions: []