swagger: "2.0"
info:
  title: FEO
  description: Provides a way to use FEO functionality programmatically rather than
    through FEO's Configuration Manager.
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /feo/v1/purge:
    post:
      summary: Purge a Configuration
      description: ""
      operationId: feov1purge
      responses:
        200:
          description: OK
      tags:
      - ""
definitions: []