swagger: "2.0"
info:
  title: PublishECCU
  description: Manage ECCU files for purging Edge content. A SOAP API.
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []