swagger: "2.0"
info:
  title: Traffic Management Load Feedback
  description: POST load data for a GTM domain and GET the current load state.
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  connections:
    get:
      summary: Fetch Load Data
      description: ""
      operationId: connections
      parameters:
      - in: Number
        name: datacenterId
        description: The ID number for the datacenter (traffic target), from the &#8220;Akamai
          code&#8221; field in the Luna Control Center.
        type: string
      - in: String
        name: domain
        description: The name of the GTM domain
        type: string
      - in: String
        name: resource
        description: The name of the resource
        type: string
      responses:
        200:
          description: OK
      tags:
      - ""
  region:
    post:
      summary: Submit Load Data
      description: ""
      operationId: region
      parameters:
      - in: Number
        name: datacenterId
        description: The ID number for the datacenter (traffic target), from the &#8220;Akamai
          code&#8221; field in the Luna Control Center.
        type: string
      - in: String
        name: domain
        description: The name of the GTM domain
        type: string
      - in: String
        name: resource
        description: The name of the resource
        type: string
      responses:
        200:
          description: OK
      tags:
      - ""
definitions: []