swagger: "2.0"
info:
  title: DNS Subdomains API
  description: Use the Subdomains operation to view information about the subdomains
    for a specified domain.
  version: 1.0.0
host: global.dns.api.rackspacecloud.com
basePath: /v2/{tenant_id}
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /v1.0/{account}/domains/{domainId}/subdomainsn:
    get:
      summary: List subdomains
      description: This call provides a list of all DNS domains that are subdomains
        for aspecified domain. The resulting list is flat, and does not break the
        domainsdown hierarchically by subdomain.Note
      operationId: list-subdomains
      parameters:
      - in: query
        name: account
        description: The tenant ID.
        type: <td>string</td>
      - in: query
        name: domainId
        description: ID for the domain.
        type: <td>string</td>
      - in: header
        name: X-Auth-Token
        description: Arbitrary characterstring generated by theauthentication servicein
          response to validcredentials.
        type: <td>string</td>
      responses:
        200:
          description: OK
      tags:
      - Subdomains
definitions: []