swagger: "2.0"
info:
  title: Current Status API
  description: The Current Status API.
  version: 1.0.0
host: www.site24x7.com.
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /current_status/type/{monitor_type}:
    get:
      summary: Current Status by Monitor Type
      description: Request Example
      operationId: current-status-by-monitor-type
      parameters:
      - in: path
        name: monitor_type
        description: MandatoryType of the monitor.  Monitor Types.
        type: <td>string</td>
      responses:
        200:
          description: OK
      tags:
      - Current Status
  /current_status/{monitor_id}:
    get:
      summary: Current Status of Monitor
      description: Request Example
      operationId: current-status-of-monitor
      parameters:
      - in: path
        name: monitor_id
        description: MandatoryUnique ID of the monitor. You can find monitor_id using
          the monitor list api.
        type: <td>string</td>
      responses:
        200:
          description: OK
      tags:
      - Current Status
definitions: []