swagger: "2.0"
info:
  title: Checks Ping API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  '/checks/ping ':
    ' post ':
      summary: Checks Ping
      description: ttttCreates a new Ping check.ttt
      operationId: -checks-ping-
      responses:
        200:
          description: OK
      tags:
      - Checks Ping
  '/checks/ping/locations ':
    ' get ':
      summary: Checks Ping Locations
      description: ttttGets a list of all locations that are available for Ping checks.ttt
      operationId: -checks-ping-locations-
      responses:
        200:
          description: OK
      tags:
      - Checks Ping
  '/checks/ping/{checkId} ':
    ' put ':
      summary: Checks Ping {checkId}
      description: ttttUpdates a Ping check.ttt
      operationId: -checks-ping-checkid-
      responses:
        200:
          description: OK
      tags:
      - Checks Ping
definitions: []