swagger: "2.0"
info:
  title: Customers API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  '/customers ':
    ' post ':
      summary: Customers
      description: ttttCreates customer.ttt
      operationId: -customers-
      responses:
        200:
          description: OK
      tags:
      - Customers
  '/customers/{customerId} ':
    ' get ':
      summary: Customers {customerId}
      description: ttttReturns subcustomer by subcustomers ID.ttt
      operationId: -customers-customerid-
      responses:
        200:
          description: OK
      tags:
      - Customers
  '/customers/{customerId}/subscription ':
    ' put ':
      summary: Customers {customerId} Subscription
      description: ttttUpdates customers subscription.ttt
      operationId: -customers-customerid-subscription-
      responses:
        200:
          description: OK
      tags:
      - Customers
definitions: []