swagger: "2.0"
info:
  title: Messages API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /buckets/{bucketKey}/messages:
    delete:
      summary: Clear a bucket (remove all messages).
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: bucketKey
        description: Unique identifier for a bucket
      responses:
        200:
          description: OK
      tags:
      - Messages
    get:
      summary: Retrieve a list of messages in a bucket
      description: ""
      operationId: ""
      parameters:
      - in: query
        name: before
        description: Only return messages before the given Unix timestamp
      - in: path
        name: bucketKey
        description: Unique identifier for a bucket
      - in: query
        name: count
        description: Maxiumum number of messages to return. Default 50, max 1000.
      - in: query
        name: since
        description: Only return messages after the given Unix timestamp
      responses:
        200:
          description: OK
      tags:
      - Messages
    post:
      summary: Create a message
      description: ""
      operationId: ""
      parameters:
      - in: body
        name: NewMessage
        schema:
          $ref: '#/definitions/holder'
      responses:
        200:
          description: OK
      tags:
      - Messages
  /buckets/{bucketKey}/messages/{messageId}:
    get:
      summary: Retrieve the details for a single message.
      description: ""
      operationId: ""
      parameters:
      - in: path
        name: bucketKey
        description: Unique identifier for a bucket
      - in: query
        name: messageId
        description: The unique identifier for this message
      responses:
        200:
          description: OK
      tags:
      - Messages
  '/messages ':
    ' post ':
      summary: Messages
      description: Creates an UI message.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Messages
  '/messages/{id} ':
    ' delete ':
      summary: Messages {id}
      description: Deletes an existing UI message.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Messages
    ' get ':
      summary: Messages {id}
      description: Gets an existing UI message by Id.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Messages
    ' put ':
      summary: Messages {id}
      description: Updates an existing UI message.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Messages
  '/messages?active={active}&amp;customerId={customerId} ':
    ' get ':
      summary: Messages?active={active}&amp;customerId={customerId}
      description: Gets a list of UI messages. UI messages are used for user notifications
        on announcements/information/warnings.ttt
      operationId: ""
      responses:
        200:
          description: OK
      tags:
      - Messages
definitions: []