swagger: "2.0"
info:
  title: Maintenance Windows API
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /maintenance_windows:
    get:
      summary: List maintenance windows
      description: List existing maintenance windows, optionally filtered by service
        and/or team, or whether they are from the past, present or future.
      operationId: list-existing-maintenance-windows-optionally-filtered-by-service-andor-team-or-whether-they-are-from
      parameters:
      - in: query
        name: filter
        description: Only return maintenance windows in a given state.
      - in: query
        name: No Name
      - in: query
        name: query
        description: Filters the results, showing only the maintenance windows whose
          descriptions contain the query.
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
    post:
      summary: Create a maintenance window
      description: Create a new maintenance window for the specified services. No
        new incidents will be created for a service that is in maintenance.
      operationId: create-a-new-maintenance-window-for-the-specified-services-no-new-incidents-will-be-created-for-a-se
      parameters:
      - in: body
        name: maintenance_window
        description: The maintenance window object.
        schema:
          $ref: '#/definitions/holder'
      - in: query
        name: No Name
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
    x-description:
      summary: L
      description: L
      operationId: L
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
  /maintenance_windows/{id}:
    delete:
      summary: Delete or end a maintenance window
      description: Delete an existing maintenance window if its in the future, or
        end it if its currently on-going. If the maintenance window has already ended
        it cannot be deleted.
      operationId: delete-an-existing-maintenance-window-if-its-in-the-future-or-end-it-if-its-currently-ongoing-if-the
      parameters:
      - in: query
        name: No Name
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
    get:
      summary: Get a maintenance window
      description: Get an existing maintenance window.
      operationId: get-an-existing-maintenance-window
      parameters:
      - in: query
        name: No Name
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
    put:
      summary: Update a maintenance window
      description: Update an existing maintenance window.
      operationId: update-an-existing-maintenance-window
      parameters:
      - in: body
        name: maintenance_window
        description: The maintenance window to be updated.
        schema:
          $ref: '#/definitions/holder'
      - in: query
        name: No Name
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
    x-description:
      summary: M
      description: M
      operationId: M
      responses:
        200:
          description: OK
      tags:
      - Maintenance Windows
definitions: []