swagger: "2.0"
info:
  title: Devices API
  description: The Devices API.
  version: 1.0.0
host: api.serverdensity.io.
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /inventory/devices:
    "":
      summary: Creating a device
      description: You can create new devices via the API, useful if you want to automatically
        provision new devices and start monitoring automatically.This API method is
        used by our Puppet manifest, Chef cookbook and installer shell script to automatically
        create devices during the agent installation.
      operationId: creating-a-device
      parameters:
      - in: body
        name: cpuCores
        description: Itemu2019s number of cores.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: group
        description: Name of group. This is set to u201cnullu201d when a device doesnu2019t
          have a group.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: hostname
        description: Deviceu2019s hostname
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: installedRAM
        description: RAM installed
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: location
        description: A dictionary containing countryCode, text (which is the city)
          and countryName
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: name
        description: Name of device.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: os
        description: A dictionary containing code and name. OS codes can be seen below
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: privateIPs
        description: Itemu2019s private IP addresses as a JSON encoded list.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: provider
        description: The provider dependent string that identifies this item. If this
          field is set, provider is mandatory.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: publicIPs
        description: Itemu2019s public IP addresses as a JSON encoded list.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: swapSpace
        description: Itemu2019s swap space
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: tags
        description: A JSON list of tag IDs.
        schema:
          $ref: '#/definitions/holder'
      - in: body
        name: token
        description: Your API token.
        schema:
          $ref: '#/definitions/holder'
      - in: query
        name: token
        description: Your API token
        type: string
      responses:
        200:
          description: OK
      tags:
      - Devices
  /inventory/devices/agentKey/byagentkey:
    "":
      summary: View device by agent key
      description: ""
      operationId: view-device-by-agent-key
      parameters:
      - in: path
        name: agentKey
        description: The key used by the agent
        type: string
      - in: path
        name: token
        description: Your API token.
        type: string
      - in: query
        name: token
        description: Your API token.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Devices
  /inventory/devices/deviceId:
    "":
      summary: Updating a device
      description: Update a device and the associated metadata.
      operationId: updating-a-device
      parameters:
      - in: path
        name: cpuCores
        description: Itemu2019s number of cores.
        type: string
      - in: body
        name: cpuCores
        description: Itemu2019s number of cores.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: deviceId
        description: The ID of the device to update.
        type: string
      - in: path
        name: group
        description: Name of group. This is set to u201cnullu201d when a device doesnu2019t
          have a group.
        type: string
      - in: body
        name: group
        description: Name of group. This is set to u201cnullu201d when a device doesnu2019t
          have a group.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: hostname
        description: Itemu2019s hostname.
        type: string
      - in: body
        name: hostname
        description: Itemu2019s hostname.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: installedRAM
        description: RAM installed.
        type: string
      - in: body
        name: installedRAM
        description: RAM installed.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: name
        description: Name of the device.
        type: string
      - in: body
        name: name
        description: Name of the device.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: os
        description: Operating system that it runs.
        type: string
      - in: body
        name: os
        description: Operating system that it runs.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: privateIPs
        description: Itemu2019s private IP addresses as a JSON encoded list.
        type: string
      - in: body
        name: privateIPs
        description: Itemu2019s private IP addresses as a JSON encoded list.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: provider
        description: Provider where the item is hosted. For cloud items it may be
          u2018amazonu2019, u2018googleu2019 or u2018rackspaceu2019.
        type: string
      - in: body
        name: provider
        description: Provider where the item is hosted. For cloud items it may be
          u2018amazonu2019, u2018googleu2019 or u2018rackspaceu2019.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: providerId
        description: The provider dependent string that identifies this item. If this
          field is set, provider is mandatory.
        type: string
      - in: body
        name: providerId
        description: The provider dependent string that identifies this item. If this
          field is set, provider is mandatory.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: publicIPs
        description: Itemu2019s public IP addresss as a JSON encoded list.
        type: string
      - in: body
        name: publicIPs
        description: Itemu2019s public IP addresss as a JSON encoded list.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: swapSpace
        description: Itemu2019s swap space.
        type: string
      - in: body
        name: swapSpace
        description: Itemu2019s swap space.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: tags
        description: A JSON list of tag IDs.
        type: string
      - in: body
        name: tags
        description: A JSON list of tag IDs.
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: token
        description: Your API token.
        type: string
      - in: body
        name: token
        description: Your API token.
        schema:
          $ref: '#/definitions/holder'
      responses:
        200:
          description: OK
      tags:
      - Devices
definitions: []