swagger: "2.0"
info:
  title: Service Status API
  description: The Service Status API.
  version: 1.0.0
host: api.serverdensity.io.
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /alerts/service_alerts.json:
    "":
      summary: Listing service alert metrics
      description: Devices and services have different alert metrics which you can
        configure in the ui. The section correspond to the top-level of the alert
        metric whereas field corresponds to the subsection of the given section.
      operationId: listing-service-alert-metrics
      parameters:
      - in: query
        name: token
        description: Your API token
        type: string
      responses:
        200:
          description: OK
      tags:
      - Alerts
  /service-monitor/last/serviceId:
    "":
      summary: Location service status (last)
      description: Get the current results from a service check.
      operationId: location-service-status-last
      parameters:
      - in: path
        name: serviceId
        description: The ID of the service to retrieve the details for.
        type: string
      - in: path
        name: token
        description: Your API token.
        type: string
      - in: query
        name: token
        description: Your API token.
        type: string
      responses:
        200:
          description: OK
      tags:
      - Service Monitor
definitions: []