swagger: "2.0"
info:
  title: Organization API
  description: For managing organizations.
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /org/asns:
    get:
      summary: List ASNS
      description: ' lists the ASNs associated with a given organization.'
      operationId: orgAsns
      responses:
        200:
          description: OK
      tags:
      - ASNs
  /org/nets:
    get:
      summary: List Nets
      description: lists the networks associated with a given organization.
      operationId: orgNets
      responses:
        200:
          description: OK
      tags:
      - Nets
  /org/pocs:
    get:
      summary: List POCs
      description: lists the POCs associate with a given organization.
      operationId: orgPocs
      responses:
        200:
          description: OK
      tags:
      - POCs
  /orgs:
    get:
      summary: Manages organizations
      description: ""
      operationId: organizations
      parameters:
      - in: query
        name: dba
        description: the name the organization does business as
        type: string
        format: string
      - in: query
        name: handle
        description: the handle of the organization
        type: string
        format: string
      - in: query
        name: name
        description: the name of organization
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - Organizations
definitions: []