swagger: "2.0"
info:
  title: Point of Contact (POC) API
  description: For managing Point of Contact (POC).
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /poc:
    get:
      summary: Point of Contact (POC)
      description: lists the Point of Contact (POC)
      operationId: poc
      parameters:
      - in: query
        name: city
        description: the city registered by the POC
        type: string
        format: string
      - in: query
        name: company
        description: the company name registered by the POC
        type: string
        format: string
      - in: query
        name: domain
        description: the domain of the email address for the POC
        type: string
        format: string
      - in: query
        name: first
        description: the first name of the POC
        type: string
        format: string
      - in: query
        name: handle
        description: the handle of the POC
        type: string
        format: string
      - in: query
        name: last
        description: the last name of the POC
        type: string
        format: string
      - in: query
        name: middle
        description: the middle name of the POC
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - Point of Contact
  /poc/asns:
    get:
      summary: ASNs
      description: lists the ASNs associated with a given POC.
      operationId: pocAsns
      responses:
        200:
          description: OK
      tags:
      - ASN
  /poc/nets:
    get:
      summary: Nets
      description: lists the networks associated with a given POC.
      operationId: pocNets
      responses:
        200:
          description: OK
      tags:
      - Nets
  /poc/org:
    get:
      summary: Organizations
      description: lists the organizations associated with a given POC.
      operationId: pocOrg
      responses:
        200:
          description: OK
      tags:
      - Organizations
definitions: []