swagger: "2.0"
info:
  title: Reverse DNS API
  description: For managing reverse DNS.
  version: 1.0.0
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /rdns:
    get:
      summary: Reverse DNS
      description: ""
      operationId: rdns
      parameters:
      - in: query
        name: delegation name
        description: the name of the delegation
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - Reverse DNS
  /rdns/nets:
    get:
      summary: List Nets
      description: lists networks related to a give delegation.
      operationId: rdnsNets
      responses:
        200:
          description: OK
      tags:
      - RDNS
definitions: []