swagger: "2.0"
info:
  title: Domain Profile API
  description: Basic registrant, server, and registration data for a domain name,
    plus preview data for other products
  version: 1.0.0
host: api.domaintools.com
basePath: v1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /{domain}:
    get:
      summary: Domain Profile
      description: Basic registrant, server, and registration data for a domain name,
        plus preview data for other products
      operationId: domainProfile
      parameters:
      - in: path
        name: domain
        description: The domain to profile.
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - Domains
definitions: []