swagger: "2.0"
info:
  title: Domain Suggestions API
  description: Generates available domain suggestions that are related to a query
    string
  version: 1.0.0
host: api.domaintools.com
basePath: /v1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /domain-suggestions/:
    get:
      summary: Domain Suggestions
      description: Generates available domain suggestions that are related to a query
        string
      operationId: domainSuggestions
      parameters:
      - in: query
        name: query
        description: Query string u2014 must be at least two characters long. Use
          spaces to separate multiple terms, but be sure to URL encode the values
          before passing them to the API.
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - Domain Suggestions
definitions: []