swagger: "2.0"
info:
  title: IP Monitor API
  description: Receive notification when there are new and/or deleted domains on a
    given IP Address
  version: 1.0.0
host: api.domaintools.com
basePath: /v1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /ip-monitor/:
    get:
      summary: IP Monitor
      description: Receive notification when there are new and/or deleted domains
        on a given IP Address
      operationId: ipMonitor
      parameters:
      - in: query
        name: days_back
        description: Use this parameter in exceptional circumstances where you need
          to search domain changes up to six days prior to the current date. Set the
          value to an integer in the range of 1-6. (default 0)
        type: string
        format: string
      - in: query
        name: page
        description: If the result set is larger than 1000 records for a given day,
          request additional pages with this parameter. Set the value to an integer
          up to a maximum of the returned page_count value. (default 1)
        type: string
        format: string
      - in: query
        name: query
        description: The IP Address you wish to query ( i.e. 65.55.53.233 ).
        type: string
        format: string
      responses:
        200:
          description: OK
      tags:
      - IP Monitor
definitions: []