swagger: "2.0"
info:
  title: Parsed Whois API
  description: The DomainTools API is organized into distinct products with queries
    that follow a RESTful URL structure wherever possible. Each product offers free,
    un-authenticated access for the sample URLs listed with each product. If you haven't
    already, you may want to review the getting started document to learn about authentication
    and response formats. The Parsed Whois API provides parsed information extracted
    from the raw Whois record. The API is optimized to quickly retrieve the Whois
    record, group important data together and return a well-structured format. The
    Parsed Whois API is ideal for anyone wishing to search for, index, or cross-reference
    data from one or multiple Whois records.
  version: 1.0.0
host: api.domaintools.com
basePath: /v1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /{domain}/whois/parsed:
    get:
      summary: Parsed Whois
      description: The Parsed Whois API provides parsed information extracted from
        the raw Whois recor
      operationId: parsedWhois
      responses:
        200:
          description: OK
      tags:
      - Whois
definitions: []